version: "3"
services:
  onvifmgr:
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    devices:
      - "/dev/snd:/dev/snd"